// <auto-generated />
namespace ScaleModelsStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MultipleAddress2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MultipleAddress2));
        
        string IMigrationMetadata.Id
        {
            get { return "201807211120400_Multiple-Address-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
